<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJ5efch2\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJ5efch2/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerJ5efch2.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerJ5efch2\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerJ5efch2\appProdProjectContainer(array(
    'container.build_hash' => 'J5efch2',
    'container.build_id' => '650060df',
    'container.build_time' => 1545214782,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerJ5efch2');
